### ISSUE TITLE
MacOS Instructions (More of a Question)

### ISSUE THREAD

**Issue by mrunion** [PMunch/wxnim#31]
There is an old PR here https://github.com/PMunch/wxnim/pull/27 that seems to have added support and instructions for MacOS. The instructions haven't been incorporated, but has anything else? I know WxWidgets works on MacOS, but does wxnim with on MacOS?

Sorry for the question, but I don't want to start down a dead-end path.

**Comment by PMunch** [comment]
Hmm, I don't actually remember why that never got merged. If you try it and it still works I'd be up for merging it now.

WxNim works fine, and there's no reason why it shouldn't work on Mac since it's basically just a thin wrapper over WxWidgets (and a dash of macro-magic for genui). That being said the original bindings are a bit behind modern Nim, so I don't think they run on the 2.0 branch. I plan to update them at some point, but I was really thinking of upgrading Futhark to deal with C++ code to do it. So at the moment you have to use the 1.4 or 1.6 branch if you want to use wxNim.

**Comment by mrunion** [comment]
Thank you for the information and clarity. I appreciate your effort and the time it takes to maintain things like this.

Futhark looks very interesting, so I hope you are successful with that endeavor!
